name: Check Syntax and Style with StyleCop Analyz

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Install StyleCop Analyzers
        run: |
          cd RentAdminApp
          dotnet add package StyleCop.Analyzers --version 1.1.118
     
      - name: Build and Analyze with StyleCop
        run: |
          cd RentAdminApp
          dotnet analyze --configuration Release

      - name: Check Code Style
        run: |
          cd RentAdminApp
          dotnet style
          dotnet build --configuration Release

